sudo: false
branches:
  only:
    - master
language: nodejs
node_js:
    - 10
install:
    - npm install
notifications:
    - https://hook.bearychat.com/=bwA22/travis/52fa443470377f35e5a3d068b8d2d5ca
    - https://hook.bearychat.com/=bwA7K/travis/3c04d191a6066d3e178ab8d93643e708
jobs:
    include:
        - stage: Build
          name: Upload dist to CDN
          script:
            - npm run build
            - cd dist
            - tar -cvf neditor.tar ./ && xz -z9 neditor.tar
            - sh -c "curl -T neditor.tar.xz http://v0.api.upyun.com/notadd/download/neditor/Neditor-next-master.tar.xz -u "$UPYUN" -v;  fi"
            - echo "demo.neditor.notadd.com" > CNAME
deploy:
    provider: pages
    repo: notadd/neditor
    skip-cleanup: true
    github-token: $GITHUB_PUBLISH_TOKEN
    keep-history: true
    local-dir: dist
    target-branch: gh-pages
    name: Notadd Bot
    verbose: true
    on:
        repo: notadd/neditor
        branch: master
