security:
  basic:
    enabled: true
  user:
    password: password
  oauth2:
    resource:
      id: service
      user-info-uri: http://localhost:8180/api/users/current

spring:
  profiles:
    include: common
  application:
    name: api

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
  build:
    groupId: "@project.groupId@"
    artifact: "@project.artifactId@"
    name: "@project.name@"
    version: '@project.version@'
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}