spring:
  profiles:
    include: common
  application:
    name: api

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
  build:
    groupId: "@project.groupId@"
    artifact: "@project.artifactId@"
    name: "@project.name@"
    version: '@project.version@'
  git:
    branch: ${git.branch}
    commit:
      id: ${git.commit.id}
      time: ${git.commit.time}
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}

# 获取更全面的git信息
management:
  info:
    git:
      mode: full
  security:
    enabled: false