server:
  port: 8183
  servlet:
    context-path: /task

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/thymelte?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 19941017
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validation-query: SELECT 1
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 3
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      remove-abandoned: true
      remove-abandoned-timeout: 180
      connection-properties: clientEncoding=UTF-8
      test-while-idle: false
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # filters: stat,wall,log4j
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
          db-type: mysql
          config:
            multi-statement-allow: true
            drop-table-allow: false
        log4j:
          enabled: true
      use-global-data-source-stat: true
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        #        login-username: simon
        #        login-password: 19961120
        reset-enable: true
        allow: 127.0.0.1
        url-pattern: /druid/*
  quartz:
    job-store-type: jdbc #数据库方式
    jdbc:
      initialize-schema: never #不初始化表结构
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO #默认主机名和时间戳生成实例ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应qrtz_scheduler_state INSTANCE_NAME字段
            #instanceName: clusteredScheduler #quartzScheduler
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX #持久化配置
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #我们仅为数据库制作了特定于数据库的代理
            useProperties: false #以指示JDBCJobStore将JobDataMaps中的所有值都作为字符串，因此可以作为名称 - 值对存储而不是在BLOB列中以其序列化形式存储更多复杂的对象。从长远来看，这是更安全的，因为您避免了将非String类序列化为BLOB的类版本问题。
            tablePrefix: QRTZ_  #数据库表前缀
            misfireThreshold: 60000 #在被认为“失火”之前，调度程序将“容忍”一个Triggers将其下一个启动时间通过的毫秒数。默认值（如果您在配置中未输入此属性）为60000（60秒）。
            clusterCheckinInterval: 5000 #设置此实例“检入”*与群集的其他实例的频率（以毫秒为单位）。影响检测失败实例的速度。
            isClustered: true #打开群集功能
          threadPool: #连接池
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  jpa:
    hibernate:
      naming:
        #解决如果Column注解定义的字段名和属性名一样，会被忽略的问题。
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none #validate
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

# mybatis配置
mybatis:
  check-config-location: false
  type-aliases-package: ${base.package}.model
  configuration:
    map-underscore-to-camel-case: true
    # 二级缓存的总开关
    cache-enabled: false
  mapper-locations: classpath:mapping/*.xml

#pagehelper分页插件
pagehelper:
  #禁用reasonable分页参数合理化，页码小于1或者大于最大页码返回空数据
  reasonable: false
  params: count=countSql
  # oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012
  helper-dialect: mysql
  support-methods-arguments: true

swagger2:
  title: restful api documentation
  description: api service for app
  terms-of-service-url: NO terms of service
  version: 1.0
  contact:
    name: jeesun
    url: http://www.cnblogs.com/rainmer/
    email: simon.sun.dev@hotmail.com
  license: The Apache License, Version 2.0
  license-url: http://www.apache.org/licenses/LICENSE-2.0.html