spring:
  datasource:
    # Oracle连接信息
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: yuhang #明文thymelte
    password: yuhang #明文thymelte123456
    druid:
      validation-query: select 1 from dual
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect

#pagehelper分页插件
pagehelper:
  #禁用reasonable分页参数合理化，页码小于1或者大于最大页码返回空数据
  reasonable: false
  params: count=countSql
  # oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012
  helper-dialect: oracle
  support-methods-arguments: true